import type { Metadata } from "next";
import LegalPage, { LegalSection } from "../legalPage";
import { ORG_NAME, SITE_NAME } from "@/lib/seo";

export const metadata: Metadata = {
    title: "Terms of Service",
    description: "The terms that govern your use of Saturn.",
    alternates: { canonical: "/terms" },
};

const CONTACT_EMAIL = "lucas.marta0799@gmail.com";

export default function Terms() {
    return (
        <LegalPage title={"Terms of Service"}>
            <LegalSection heading={"1. Agreement"}>
                <p>
                    {SITE_NAME} is operated by {ORG_NAME}. By using {SITE_NAME} you agree to
                    these terms. If you do not agree, do not use the service.
                </p>
            </LegalSection>
            <LegalSection heading={"2. Service"}>
                <p>
                    {SITE_NAME} is a platform for building and scheduling agentic workflows.
                    Features may change, be added, or be removed at any time.
                </p>
            </LegalSection>
            <LegalSection heading={"3. Account"}>
                <p>
                    Sign in is via Google. You are responsible for your account and for
                    everything done with it.
                </p>
            </LegalSection>
            <LegalSection heading={"4. Acceptable use"}>
                <p>
                    Do not use {SITE_NAME} for anything unlawful, do not abuse or disrupt the
                    service, and do not use workflows to harm, spam, or gain unauthorized
                    access to third parties. Your workflows must comply with the terms of the
                    services they call. We may suspend accounts that violate this section.
                </p>
            </LegalSection>
            <LegalSection heading={"5. Your content"}>
                <p>
                    You own your workflows and data. You grant us the limited license needed
                    to store and execute them in order to provide the service.
                </p>
            </LegalSection>
            <LegalSection heading={"6. Third-party services and model output"}>
                <p>
                    API keys, MCP servers, and webhooks you connect are governed by their
                    providers&apos; terms, and you are responsible for how your workflows use
                    them. Model output is generated by third-party models; review it before
                    relying on it.
                </p>
            </LegalSection>
            <LegalSection heading={"7. Paid plans"}>
                <p>
                    Paid tiers are billed monthly through Stripe and renew automatically. You
                    can cancel anytime; access continues until the end of the paid period.
                    Model credits reset each billing period and do not roll over. Tier limits
                    and pricing may change with notice.
                </p>
            </LegalSection>
            <LegalSection heading={"8. Termination"}>
                <p>
                    You may stop using {SITE_NAME} and delete your workflows at any time. We
                    may suspend or terminate accounts that violate these terms.
                </p>
            </LegalSection>
            <LegalSection heading={"9. Disclaimer and liability"}>
                <p>
                    {SITE_NAME} is provided as is, without warranties of any kind. To the
                    maximum extent permitted by law, our total liability is capped at the
                    fees you paid us in the 12 months before the claim.
                </p>
            </LegalSection>
            <LegalSection heading={"10. Changes"}>
                <p>
                    We may update these terms. Updates are posted on this page, and continued
                    use after an update means you accept it.
                </p>
            </LegalSection>
            <LegalSection heading={"11. Governing law"}>
                <p>
                    These terms are governed by the laws of the State of California, United
                    States.
                </p>
            </LegalSection>
            <LegalSection heading={"12. Contact"}>
                <p>
                    <a href={`mailto:${CONTACT_EMAIL}`}
                       className={"underline underline-offset-4 hover:text-foreground transition-colors"}>
                        {CONTACT_EMAIL}
                    </a>
                </p>
            </LegalSection>
        </LegalPage>
    );
}
